apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray
  template:
    metadata:
      labels:
        app: ray
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: ray
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: nginx-config-vol
            mountPath: /etc/nginx/conf.d/ray.conf
            subPath: nginx.conf
          - name: xray-config-vol
            mountPath: /xraybin/config.json
            subPath: Xray.json
        env:
        - name: V2RAY_VMESS_AEAD_FORCED
          value: 'false'
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "$ProxySite"
        - name: Vless_UUID
          value: "$Vless_UUID"
        - name: Vless_Path
          value: "$Vless_Path"
        - name: Vmess_UUID
          value: "$Vmess_UUID"
        - name: Vmess_Path
          value: "$Vmess_Path"
        - name: Share_Path
          value: "$Share_Path"
      volumes:
        - name: nginx-config-vol
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: xray-config-vol
          configMap:
            name: xray-config
            items:
              - key: Xray.json
                path: Xray.json
